name: Push to NuGet

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src
    - name: NuGet Push
      env:
        SOURCE_URL: https://api.nuget.org/v3/index.json
      run: dotnet nuget push --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.SOURCE_URL }} **/*.nupkg
      working-directory: src
